as yet unclassified
months: anArrayOfString

	"An array containing the months names. Corresponds to the %B format in Highcharts.dateFormat() . Defaults to [ &quot;January&quot; , &quot;February&quot; , &quot;March&quot; , &quot;April&quot; , &quot;May&quot; , &quot;June&quot; , &quot;July&quot; , &quot;August&quot; , &quot;September&quot; , &quot;October&quot; , &quot;November&quot; , &quot;December&quot;] .
	-user"

	configurationOptions at: 'months' put: anArrayOfString