as yet unclassified
shortMonths: anArrayOfString

	"An array containing the months names in abbreviated form. Corresponds to the %b format in Highcharts.dateFormat() .  Defaults to [ &quot;Jan&quot; , &quot;Feb&quot; , &quot;Mar&quot; , &quot;Apr&quot; , &quot;May&quot; , &quot;Jun&quot; , &quot;Jul&quot; , &quot;Aug&quot; , &quot;Sep&quot; , &quot;Oct&quot; , &quot;Nov&quot; , &quot;Dec&quot;] .
	-user"

	configurationOptions at: 'shortMonths' put: anArrayOfString