as yet unclassified
style: aCSSObject

	"Additional CSS styles to apply inline to the container div . Note that since the default font styles are applied in the renderer, it is ignorant of the individual chart  options and must be set globally. Defaults to: style: {
	fontFamily: '&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Verdana, Arial, Helvetica, sans-serif', // default font
	fontSize: '12px'
}
	-user"

	configurationOptions at: 'style' put: aCSSObject