as yet unclassified
symbol: aString

	"A predefined shape or symbol for the marker. When null, the symbol is pulled from options.symbols. Other possible values are &quot;circle&quot;, &quot;square&quot;, &quot;diamond&quot;, &quot;triangle&quot; and &quot;triangle-down&quot;. Additionally, the URL to a graphic can be given on this form:  &quot;url(graphic.png)&quot;. Note that for the image to be applied to exported charts, its URL needs to be accessible by the export server.
	-user"

	configurationOptions at: 'symbol' put: aString