as yet unclassified
categories: anArray

	"If categories are present for the xAxis, names are used instead of numbers for that axis. Since Highcharts 3.0, categories can also be extracted by giving each point a name and setting axis type to &quot;category&quot; . Example: categories: ['Apples', 'Bananas', 'Oranges'] Defaults to null <p />
	-user"

	configurationOptions at: 'categories' put: anArray