as yet unclassified
type: aString

	"The type of axis. Can be one of &quot;linear&quot; , &quot;logarithmic&quot; , &quot;datetime&quot; or &quot;category&quot; . In a datetime axis, the numbers are given in milliseconds, and tick marks are placed 		on appropriate values like full hours or days. In a category axis, the point names of the chart's series are used for categories, if not a categories array is defined. Defaults to linear .
	-user"

	configurationOptions at: 'type' put: aString