as yet unclassified
crosshairs: aMixed

	"Display crosshairs to connect the points with their corresponding axis values. The crosshairs can be defined as a boolean, an array of booleans or an object. Boolean If the crosshairs option is true, a single crosshair relating to the 	x axis will be shown. Array of booleans In an array of booleans, the first value turns on the x axis crosshair and the second 	value to the y axis crosshair. Use [true, true] to show complete crosshairs. Array of objects In an array of objects, the first value applies to the x axis crosshair and the second 	value to the y axis crosshair. For each dimension, a width , color , dashStyle and zIndex can be given. Defaults to null .
	-user"

	configurationOptions at: 'crosshairs' put: aMixed